project:
  type: website
  output-dir: docs

website:
  title: "bittnation.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Projects.qmd
      - Research.qmd
      - cv.qmd

format:
  html:
    theme: Morph
    css: styles.css        
    toc: true
    page-layout: full
    includes:
      in-header: fonts.hrml

editor: visual

includes:
  in-header: fonts.hrml


